import "./globals.css";
import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import NextAuthSessionProvider from "./providers/sessionProvider";
import { authOptions } from "./api/auth/[...nextauth]/route";
import Signin from "./signin/page";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  return (
    <html>
      <body>
        {session ? (
          <NextAuthSessionProvider>
            <div>{children}</div>
          </NextAuthSessionProvider>
        ) : (
          <Signin />
        )}
      </body>
    </html>
  );
}
